export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCEESS = "FETCH_USER_SUCCEESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USERI_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USERI_SUCCEESS = "FETCH_USER_SUCCEESS";
export const FETCH_USERI_FAILURE = "FETCH_USER_FAILURE";
